In [1]:
#import all needed libraries
import numpy as np
import pandas as pd
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import make_scorer
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.layers import Input, Dense
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from sklearn.metrics import calinski_harabasz_score
import seaborn as sns
from sklearn.neighbors import LocalOutlierFactor
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

In [3]:
#Read the dataset
df1 = pd.read_csv('/Users/sushiljangid/Desktop/Final Thesis Docs/Dataset/DB elder monitoring/database_gas.csv')
df2 = pd.read_csv('/Users/sushiljangid/Desktop/Final Thesis Docs/Dataset/DB elder monitoring/database_pos.csv')

In [4]:
#First 5 rows of dataset 1
df1.head()

,timestamp,temperature,humidity,CO2CosIRValue,CO2MG811Value,MOX1,MOX2,MOX3,MOX4,COValue
0,2019-11-06 11:37:13.038174+01:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
1,2019-11-06 11:37:32.744996+01:00,19.59,54.23,129.0,563.0,477.0,731.0,649.0,565.0,125.0
2,2019-11-06 11:37:53.018087+01:00,19.63,54.05,128.0,566.0,478.0,732.0,649.0,565.0,125.0
3,2019-11-06 11:38:13.093151+01:00,19.64,53.74,128.0,566.0,478.0,732.0,649.0,565.0,125.0
4,2019-11-06 11:38:33.032832+01:00,19.67,53.53,128.0,569.0,480.0,732.0,650.0,565.0,125.0

In [5]:
#First 5 rows of dataset 2
df2.head()

,datetime,Living room,Bedroom,Bathroom,Kitchen,Hallway
0,2019-11-01 02:52:55.271086300+00:00,NaN,0.0,NaN,NaN,NaN
1,2019-11-01 03:19:57.417067700+00:00,NaN,1.0,NaN,NaN,NaN
2,2019-11-01 03:21:53.257070700+00:00,NaN,0.0,NaN,NaN,NaN
3,2019-11-01 05:11:08.874031+00:00,NaN,1.0,NaN,NaN,NaN
4,2019-11-01 05:12:38.437033500+00:00,NaN,0.0,NaN,NaN,NaN

In [6]:
# Parse timestamps as datetime objects
df1['timestamp'] = pd.to_datetime(df1['timestamp'], utc=True)
df2['datetime'] = pd.to_datetime(df2['datetime'], utc=True)

In [7]:
# Merge the datasets on the nearest timestamps
merged_data = pd.merge_asof(df2.sort_values('datetime'), df1.sort_values('timestamp'),
                            left_on='datetime', right_on='timestamp', direction='nearest')

In [8]:
#First 50 rows
merged_data.head(50)

,datetime,Living room,Bedroom,Bathroom,Kitchen,Hallway,timestamp,temperature,humidity,CO2CosIRValue,CO2MG811Value,MOX1,MOX2,MOX3,MOX4,COValue
0,2019-11-01 02:52:55.271086300+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
1,2019-11-01 03:19:57.417067700+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
2,2019-11-01 03:21:53.257070700+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
3,2019-11-01 05:11:08.874031+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
4,2019-11-01 05:12:38.437033500+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
5,2019-11-01 05:14:15.993041400+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
6,2019-11-01 05:15:16.193075900+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
7,2019-11-01 05:19:56.796071400+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
8,2019-11-01 05:21:16.204047100+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
9,2019-11-01 06:42:17.866021800+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
10,2019-11-01 06:44:19.423095700+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
11,2019-11-01 06:44:40.501085400+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
12,2019-11-01 06:44:46.413047100+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
13,2019-11-01 06:45:48.408012100+00:00,NaN,NaN,0.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
14,2019-11-01 06:46:17.569052900+00:00,NaN,NaN,1.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
15,2019-11-01 07:00:15.210071600+00:00,NaN,NaN,0.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
16,2019-11-01 07:00:17.501032300+00:00,NaN,NaN,1.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
17,2019-11-01 07:04:21.062036200+00:00,NaN,NaN,0.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
18,2019-11-01 07:12:34.973078200+00:00,NaN,NaN,NaN,NaN,1.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
19,2019-11-01 07:12:39.065045400+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
20,2019-11-01 07:12:39.442017800+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
21,2019-11-01 07:13:40.446027800+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
22,2019-11-01 07:13:41.397048700+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
23,2019-11-01 07:14:05.187063600+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
24,2019-11-01 07:14:05.633024200+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
25,2019-11-01 07:15:01.472071400+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
26,2019-11-01 07:15:06.391040+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
27,2019-11-01 07:15:06.711054+00:00,NaN,NaN,NaN,NaN,1.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
28,2019-11-01 07:15:10.238058800+00:00,NaN,1.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
29,2019-11-01 07:16:07.751083200+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
30,2019-11-01 07:16:11.142072800+00:00,NaN,0.0,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
31,2019-11-01 07:16:40.416001600+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
32,2019-11-01 07:20:52.712057800+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
33,2019-11-01 07:20:57.146056500+00:00,NaN,NaN,NaN,NaN,1.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
34,2019-11-01 07:21:54.679077500+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
35,2019-11-01 07:21:57.453068600+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
36,2019-11-01 08:37:06.403038800+00:00,NaN,NaN,NaN,NaN,1.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
37,2019-11-01 08:37:11.092019200+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
38,2019-11-01 08:38:07.677097600+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
39,2019-11-01 08:38:12.633020400+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
40,2019-11-01 08:44:36.636009400+00:00,NaN,NaN,NaN,0.0,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
41,2019-11-01 08:48:17.034095100+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
42,2019-11-01 08:49:01.663023500+00:00,NaN,NaN,NaN,1.0,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
43,2019-11-01 08:49:49.632008600+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
44,2019-11-01 08:49:57.991032400+00:00,1.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
45,2019-11-01 08:50:08.084076600+00:00,NaN,NaN,NaN,NaN,1.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
46,2019-11-01 08:50:12.145028400+00:00,NaN,NaN,1.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
47,2019-11-01 08:50:59.344005200+00:00,0.0,NaN,NaN,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
48,2019-11-01 08:51:08.622022100+00:00,NaN,NaN,NaN,NaN,0.0,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0
49,2019-11-01 08:51:40.245081600+00:00,NaN,NaN,0.0,NaN,NaN,2019-11-06 10:37:13.038174+00:00,19.48,54.86,128.0,563.0,476.0,731.0,649.0,565.0,128.0

In [9]:
#Shape of Dataset
merged_data.shape

(28478, 16)

In [10]:
# Fill missing values in the merged data using backfill
merged_data.fillna(method='ffill', inplace=True)  # Forward fill
merged_data.fillna(method='bfill', inplace=True)  # Backward fill

In [11]:
#Checking null values
merged_data.isnull().sum()

datetime         0
Living room      0
Bedroom          0
Bathroom         0
Kitchen          0
Hallway          0
timestamp        0
temperature      0
humidity         0
CO2CosIRValue    0
CO2MG811Value    0
MOX1             0
MOX2             0
MOX3             0
MOX4             0
COValue          0
dtype: int64

In [12]:
# Perform anomaly detection using Isolation Forest
features = ['temperature', 'humidity', 'CO2CosIRValue', 'CO2MG811Value', 'MOX1', 'MOX2', 'MOX3', 'MOX4', 'COValue']
X = merged_data[features]
clf = IsolationForest(contamination=0.05, random_state=42)
merged_data['anomaly'] = clf.fit_predict(X)

print(merged_data)

                                 datetime  Living room  Bedroom  Bathroom  \
0     2019-11-01 02:52:55.271086300+00:00          0.0      0.0       0.0
1     2019-11-01 03:19:57.417067700+00:00          0.0      1.0       0.0
2     2019-11-01 03:21:53.257070700+00:00          0.0      0.0       0.0
3        2019-11-01 05:11:08.874031+00:00          0.0      1.0       0.0
4     2019-11-01 05:12:38.437033500+00:00          0.0      0.0       0.0
...                                   ...          ...      ...       ...
28473 2020-02-13 17:04:38.956087800+00:00          1.0      0.0       0.0
28474 2020-02-13 17:05:29.384067600+00:00          1.0      0.0       1.0
28475 2020-02-13 17:06:21.575053600+00:00          0.0      0.0       1.0
28476 2020-02-13 17:06:30.519011100+00:00          0.0      0.0       0.0
28477 2020-02-13 17:06:30.833050100+00:00          0.0      0.0       0.0

       Kitchen  Hallway                        timestamp  temperature  \
0          0.0      0.0 2019-11-06 10:37:13.038174+00:00        19.48
1          0.0      0.0 2019-11-06 10:37:13.038174+00:00        19.48
2          0.0      0.0 2019-11-06 10:37:13.038174+00:00        19.48
3          0.0      0.0 2019-11-06 10:37:13.038174+00:00        19.48
4          0.0      0.0 2019-11-06 10:37:13.038174+00:00        19.48
...        ...      ...                              ...          ...
28473      0.0      1.0 2020-02-13 10:58:14.014336+00:00        20.62
28474      0.0      1.0 2020-02-13 10:58:14.014336+00:00        20.62
28475      0.0      1.0 2020-02-13 10:58:14.014336+00:00        20.62
28476      0.0      1.0 2020-02-13 10:58:14.014336+00:00        20.62
28477      0.0      0.0 2020-02-13 10:58:14.014336+00:00        20.62

       humidity  CO2CosIRValue  CO2MG811Value   MOX1   MOX2   MOX3   MOX4  \
0         54.86          128.0          563.0  476.0  731.0  649.0  565.0
1         54.86          128.0          563.0  476.0  731.0  649.0  565.0
2         54.86          128.0          563.0  476.0  731.0  649.0  565.0
3         54.86          128.0          563.0  476.0  731.0  649.0  565.0
4         54.86          128.0          563.0  476.0  731.0  649.0  565.0
...         ...            ...            ...    ...    ...    ...    ...
28473     57.74           63.0          518.0  524.0  698.0  641.0  591.0
28474     57.74           63.0          518.0  524.0  698.0  641.0  591.0
28475     57.74           63.0          518.0  524.0  698.0  641.0  591.0
28476     57.74           63.0          518.0  524.0  698.0  641.0  591.0
28477     57.74           63.0          518.0  524.0  698.0  641.0  591.0

       COValue  anomaly
0        128.0        1
1        128.0        1
2        128.0        1
3        128.0        1
4        128.0        1
...        ...      ...
28473    157.0        1
28474    157.0        1
28475    157.0        1
28476    157.0        1
28477    157.0        1

[28478 rows x 17 columns]

In [13]:
#Normalize the dataset
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# Define a custom scorer
def custom_scorer(clf, X, y):
    predicted_labels = clf.predict(X)
    accuracy = accuracy_score(y, predicted_labels)
    return accuracy

# Create the Isolation Forest model
clf = IsolationForest(contamination=0.05, random_state=42)

# Define the parameter grid for tuning
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_samples': [0.5, 0.8, 1.0]
}

# Create GridSearchCV with the custom scorer
grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5, scoring=make_scorer(custom_scorer))
grid_search.fit(X_scaled)

# Get the best estimator from the grid search
best_clf = grid_search.best_estimator_

In [ ]:
# Convert predictions to 0 for normal instances and 1 for anomalies
y_pred = best_clf.predict(X_scaled)
isolation_forest_outliers = [1 if label == -1 else 0 for label in y_pred]

# Ground truth labels (1 for anomalies, 0 for normal)
y_true = [1 if is_anomaly else 0 for is_anomaly in isolation_forest_outliers]

In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_true, isolation_forest_outliers)

# Calculate precision
precision = precision_score(y_true, isolation_forest_outliers)

# Calculate recall
recall = recall_score(y_true, isolation_forest_outliers)

# Calculate F1-score
f1 = f1_score(y_true, isolation_forest_outliers)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1-score: {f1:.2f}')

In [ ]:
# Print the rows where anomalies are detected (-1 indicates anomalies)
anomalies = merged_data[merged_data['anomaly'] == -1]
print("Anomalies:")
print(anomalies)

In [ ]:
#Checking the columns
merged_data.info()

In [ ]:
# Count the number of anomalies detected
num_anomalies = len(anomalies)
print(f"Number of anomalies detected: {num_anomalies}")

In [ ]:
# Analyze anomalies by specific rooms
anomalies_by_room = anomalies.groupby('Living room')['anomaly'].count()
print("Anomalies by Room:")
print(anomalies_by_room)

In [ ]:
# Analyze anomalies by Kitchen
anomalies_by_room = anomalies.groupby('Kitchen')['anomaly'].count()
print("Anomalies by Room:")
print(anomalies_by_room)

In [ ]:
#  Trigger actions based on detected anomalies
for index, row in anomalies.iterrows():
    print(f"Anomaly detected in {row['Kitchen']} at {row['timestamp']}. Triggering alert/notification...")

In [ ]:
# Statistical analysis of anomalies (mean, standard deviation, etc.)
anomalies_stats = anomalies[features].describe()
print("Anomalies Statistics:")
print(anomalies_stats)

In [ ]:
# Convert timestamp columns to datetime
merged_data['datetime'] = pd.to_datetime(merged_data['datetime'])
merged_data['timestamp'] = pd.to_datetime(merged_data['timestamp'])

In [ ]:
# Visualize anomalies in specific features (e.g., temperature)
plt.figure(figsize=(8, 6))
plt.hist(anomalies['temperature'], bins=20, color='red', alpha=0.7, label='Anomalies')
plt.hist(merged_data['temperature'], bins=20, color='blue', alpha=0.7, label='Normal')
plt.xlabel('Temperature')
plt.ylabel('Frequency')
plt.legend()
plt.title('Anomaly Detection: Temperature Distribution')
plt.show()

In [ ]:
merged_data

In [ ]:
# Visualization: Line plot for temperature variation over time
plt.figure(figsize=(12, 6))
sns.lineplot(x='datetime', y='temperature', data=merged_data)
plt.title('Temperature Variation Over Time')
plt.xlabel('Date')
plt.ylabel('Temperature')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# Visualization: Countplot for anomaly occurrences
sns.countplot(x='anomaly', data=merged_data, order=[-1, 1])
plt.title('Count of Anomalies')
plt.xlabel('Anomaly')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['Anomaly', 'Normal'])
plt.tight_layout()
plt.show()

In [ ]:
sns.violinplot(x='anomaly', y='CO2MG811Value', data=merged_data)
plt.title('CO2 Levels Anomaly Distribution')
plt.xlabel('Anomaly')
plt.ylabel('CO2 Level')
plt.show()

In [ ]:
#Lineplot
sns.lineplot(x='datetime', y='CO2MG811Value', hue='anomaly', data=merged_data, palette='winter')
plt.title('CO2 Levels Over Time')
plt.xlabel('Date and Time')
plt.ylabel('CO2 Level')
plt.xticks(rotation=45)
plt.show()

In [ ]:
#Pairplot
sns.pairplot(merged_data[['Living room', 'Bedroom', 'Bathroom', 'Kitchen', 'Hallway', 'temperature', 'humidity', 'CO2CosIRValue', 'CO2MG811Value']], diag_kind='kde')
plt.suptitle('Pairplot for Sensor Data', y=1.02)
plt.show()

In [ ]:
#Histplot
sns.histplot(merged_data['temperature'], bins=20, kde=True)
plt.title('Temperature Distribution')
plt.xlabel('Temperature')
plt.ylabel('Frequency')
plt.show()

In [ ]:
#Countplot
sns.countplot(x='Bedroom', hue='anomaly', data=merged_data)

In [ ]:
# Analyze correlations between features
import seaborn as sns
correlation_matrix = merged_data[features].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

In [ ]:
# Extract hour of the day from the timestamp and analyze anomalies by hour
anomalies['hour'] = anomalies['datetime'].dt.hour
anomalies_by_hour = anomalies.groupby('hour')['anomaly'].count()

plt.figure(figsize=(8, 6))
sns.barplot(x=anomalies_by_hour.index, y=anomalies_by_hour.values, palette='viridis')
plt.xlabel('Hour of the Day')
plt.ylabel('Number of Anomalies')
plt.title('Anomalies by Hour of the Day')
plt.show()

In [ ]:
# 'merged_data' contains  dataset and 'anomaly' variable contains the output from Isolation Forest
X = merged_data[features]
anomaly = merged_data['anomaly']

# Standardize the features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# 1. DBSCAN (Continuation)
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_std)
# -1 indicates outliers in DBSCAN
dbscan_outliers = (dbscan_labels == -1)

# Further analysis or actions based on DBSCAN anomalies
for idx, is_anomaly in enumerate(dbscan_outliers):
    if is_anomaly:
        print(f"DBSCAN Anomaly detected at index {idx}.")

In [ ]:
# Apply DBSCAN
epsilon = 0.5
min_samples = 5
dbscan = DBSCAN(eps=epsilon, min_samples=min_samples)
merged_data['cluster'] = dbscan.fit_predict(X_std)

# Anomalies will be points that are not assigned to any cluster (cluster label -1)
anomalies = merged_data[merged_data['cluster'] == -1]

# Now 'anomalies' DataFrame contains the anomalies detected by DBSCAN
print(anomalies)

In [ ]:
#Fit the dbscan
dbscan = DBSCAN(eps=epsilon, min_samples=min_samples, metric='manhattan')
merged_data['cluster'] = dbscan.fit_predict(X_std)

In [ ]:
#Silhouette score
from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(X_std, merged_data['cluster'])
print("Silhouette Score:", silhouette_avg)

In [ ]:
#calinski_harabasz_score
calinski_harabasz = calinski_harabasz_score(X_std, merged_data['cluster'])
print("Calinski-Harabasz Index:", calinski_harabasz)

In [ ]:
# Define the autoencoder model
input_layer = Input(shape=(X_std.shape[1],))
encoder = Dense(32, activation='relu')(input_layer)
encoder = Dense(16, activation='relu')(encoder)
decoder = Dense(32, activation='relu')(encoder)
decoder = Dense(X_std.shape[1], activation='linear')(decoder)

autoencoder_model = Model(inputs=input_layer, outputs=decoder)
autoencoder_model.compile(optimizer='adam', loss='mean_squared_error')

# Train the autoencoder model
autoencoder_model.fit(X_std, X_std, epochs=50, batch_size=64, shuffle=True)

# Use the trained autoencoder to predict the samples
autoencoder_preds = autoencoder_model.predict(X_std)
mse = ((X_std - autoencoder_preds) ** 2).mean(axis=1)
threshold = mse.mean() + 2 * mse.std()  # Set threshold using mean and standard deviation

# Detect outliers using autoencoder
autoencoder_outliers = (mse > threshold)

# Further analysis or actions based on autoencoder anomalies
for idx, is_anomaly in enumerate(autoencoder_outliers):
    if is_anomaly:
        print(f"Autoencoder Anomaly detected at index {idx}.")

In [ ]:
# Calculate reconstruction loss on the test set
reconstruction_loss = ((X_std - autoencoder_preds) ** 2).mean(axis=1)
print(f"Reconstruction Loss on Test Set: {reconstruction_loss.mean():.2f}")

In [ ]:
# Ground truth labels (1 for anomalies, 0 for normal)
y_true = [1 if is_anomaly else 0 for is_anomaly in autoencoder_outliers]

# Predicted labels (True for anomalies, False for normal)
y_pred = [1 if is_anomaly else 0 for is_anomaly in autoencoder_outliers]

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-score: {f1:.2f}")

In [ ]:
# Generate the confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred)
conf_matrix

In [ ]:
# Initialize the LOF model
lof = LocalOutlierFactor(n_neighbors=20, contamination=0.05)  # Adjust parameters as needed

# Fit the model and predict outliers
outliers = lof.fit_predict(X)

# 'outliers' will contain the predicted labels: 1 for inliers (normal data points), -1 for outliers (anomalies)

# Add the 'outliers' array to your original dataset if needed
merged_data['outliers'] = outliers

# Print the number of anomalies detected
num_anomalies = len(merged_data[merged_data['outliers'] == -1])
print(f'Number of anomalies detected: {num_anomalies}')

In [ ]:
# Print the number of anomalies detected
num_anomalies = len(merged_data[merged_data['outliers'] == -1])
print(f'Number of anomalies detected: {num_anomalies}')

In [ ]:
#Model Evaluation LOF
true_labels = merged_data['anomaly']
predicted_labels = merged_data['outliers']

accuracy = accuracy_score(true_labels, predicted_labels)
precision = precision_score(true_labels, predicted_labels)
recall = recall_score(true_labels, predicted_labels)
f1 = f1_score(true_labels, predicted_labels)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1-score: {f1:.2f}')

In [ ]:
# Initialize One-Class SVM model
from sklearn.model_selection import train_test_split
X_train, X_test, true_labels_train, true_labels_test = train_test_split(X_scaled, true_labels, test_size=0.2, random_state=42)

svm_model = OneClassSVM(nu=0.05, kernel='rbf', gamma=0.1)  # Adjust parameters as needed

# Fit the model only on the training data
svm_model.fit(X_train)

# Predict outliers/anomalies on the test set
predicted_labels = svm_model.predict(X_test)
predicted_labels[predicted_labels == 1] = 0  # Convert inliers to 0, outliers to -1

# Calculate evaluation metrics
accuracy = accuracy_score(true_labels_test, predicted_labels)
precision_macro = precision_score(true_labels_test, predicted_labels, average='macro')
recall_macro = recall_score(true_labels_test, predicted_labels, average='macro')
f1_macro = f1_score(true_labels_test, predicted_labels, average='macro')

# Print the evaluation metrics
print(f'Accuracy: {accuracy:.2f}')
print(f'Precision : {precision_macro:.2f}')
print(f'Recall : {recall_macro:.2f}')
print(f'F1-score : {f1_macro:.2f}')